// Package snmptrap provides SNMP trap generation, persistence, and transmission
// for simulating network device telemetry in the datasource service.
//
// NOTE: This package uses JSON-encoded traps sent over UDP rather than actual
// SNMP BER encoding. This is intentional for simulation purposes — a production
// SNMP implementation would use a library like gosnmp for proper encoding.
//
// TODO: Replace global rand usage with a *rand.Rand instance per generator to
// avoid potential race conditions when multiple goroutines generate traps
// concurrently. In Go 1.20+, prefer rand.New(rand.NewSource(...)).
package snmptrap

import (
	"math/rand"
	"time"
)

// Trap represents a single SNMP v2c trap event generated by the simulator.
type Trap struct {
	Version   string            `json:"version"`   // SNMP version (e.g. "v2c")
	Community string            `json:"community"` // SNMP community string
	OID       string            `json:"oid"`       // Object Identifier for the trap type
	Source    string            `json:"source"`     // Hostname or IP of the originating device
	Message   string            `json:"message"`    // Human-readable trap description
	Severity  string            `json:"severity"`   // Severity level: info, warning, error, critical
	Timestamp time.Time         `json:"timestamp"`  // When the trap was generated (UTC)
	Variables map[string]string `json:"variables"`  // Variable bindings (OID → value pairs)
}

// RandomTrap generates a random SNMP trap for the given device type and source.
// Supported device types are "router", "switch", and "firewall"; unknown types
// default to router templates.
func RandomTrap(deviceType string, source string) Trap {
	var templates []TrapTemplate

	switch deviceType {
	case "router":
		templates = RouterTraps
	case "switch":
		templates = SwitchTraps
	case "firewall":
		templates = FirewallTraps
	default:
		templates = RouterTraps
	}

	t := templates[rand.Intn(len(templates))]

	return Trap{
		Version:   "v2c",
		Community: "public",
		OID:       t.OID,
		Source:    source,
		Message:   t.Message,
		Severity:  t.Severity,
		Timestamp: time.Now().UTC(),
		Variables: map[string]string{
			"ifIndex": "1",
			"value":   "threshold-crossed",
		},
	}
}
